DROP TABLE IF EXISTS "user_skins" CASCADE;
DROP TABLE IF EXISTS "skin_purchase_history" CASCADE;
DROP TABLE IF EXISTS "transaction" CASCADE;
DROP TABLE IF EXISTS "statistics" CASCADE;
DROP TABLE IF EXISTS "skins" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;