CREATE TABLE IF NOT EXISTS "users" (
    "id" SERIAL PRIMARY KEY,
    "nickname" VARCHAR UNIQUE NOT NULL,
    "email" VARCHAR UNIQUE NOT NULL,
    "password_hash" VARCHAR NOT NULL,
    "role" VARCHAR NOT NULL,
    "gems" INTEGER NOT NULL DEFAULT 0
);